default: &default
  pool: 5
  adapter: mysql2
  encoding: utf8mb4
  
development:
  <<: *default
  database: myapp_development
  adapter: mysql2
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>
  host: <%= ENV.fetch("MYSQL_HOST", "localhost") %>
  socket: <%= ENV["MYSQL_SOCKET"] %>

test:
  <<: *default
  database: myapp_test
  adapter: mysql2
  host: localhost
  socket: <%= ENV["MYSQL_SOCKET"] %>
  username: root

production:
  <<: *default
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  socket: <%= ENV['MYSQL_SOCKET'] %>
