# config/plans.yml

tepco:
  name: "東京電力エナジーパートナー"
  plan:
    name: "従量電灯B"
    base_price:
      "10": 28.60
      "15": 42.90
      "20": 57.20
      "30": 85.80
      "40": 114.40
      "50": 143.00
      "60": 171.60
    step:
      1:
        range: 0..120
        price: 19.88
      2:
        range: 121..300
        price: 26.48
      3:
        range: 301..Float::INFINITY
        price: 30.57

looop:
  name: "Looop"
  plan:
    name: "基本料金(10A~60A)"
    base_price:
      "10": 0.0
      "15": 0.0
      "20": 0.0
      "30": 0.0
      "40": 0.0
      "50": 0.0
      "60": 0.0
    step:
      1:
        range: 0..Float::INFINITY
        price: 26.40

shinshu:
  name: "東京電力エナジーパートナー"
  plan:
    name: "ずっとも電気1の基本料金(月ごと)"
    base_price:
      "30": 858.0
      "40": 1144.0
      "50": 1430.0
      "60": 1716.0
    step:
      1:
        range: 0..140
        price: 23.67
      2:
        range: 141..350
        price: 23.88
      3:
        range: 351..Float::INFINITY
        price: 26.41

jxtg:
  name: "JXTGでんき (lEｍyでんき)"
  plan:
    name: "電力料金(月ごと)"
    base_price:
      "30": 858.0
      "40": 1144.0
      "50": 1430.0
      "60": 1716.0
    step:
      1:
        range: 0..120
        price: 19.88
      2:
        range: 121..300
        price: 26.48
      3:
        range: 301..600
        price: 25.90
      4:
        range: 601..Float::INFINITY
        price: 26.15
