FROM ruby:3.1

ARG LANG=C.UTF-8
ARG TZ=Asia/Tokyo

ARG RAILS_ENV=production
ARG RAILS_MASTER_KEY=b21bb0d9a126145ab705ace96208344d
ARG MYSQL_SOCKET=/cloudsql/btob-371706:asia-northeast1:b2b-app
ARG MYSQL_HOST=localhost
ARG MYSQL_DATABASE=prod_db
ARG MYSQL_USER=prod_user
ARG MYSQL_ROOT_PASSWORD=gcp-sample
ARG RAILS_LOG_TO_STDOUT=true
ARG RAILS_SERVE_STATIC_FILES=true

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -qq \
    && apt-get install -y nodejs yarn

WORKDIR /myapp
COPY . /myapp

RUN bundle install -j 4

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 8080

CMD ["rails", "server", "-p", "8080", "-b", "0.0.0.0"]
