source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.1"
gem 'rails', '~> 7.0'

gem "sprockets-rails"
gem "puma", "~> 5.0"

gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false

gem "slim-rails"
gem 'tailwindcss-rails'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "mysql2", "~> 0.5"
end

group :development do
  gem "web-console"
  gem "rack-mini-profiler"
  gem "spring"
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring-commands-rspec'
  gem 'spring'
end

group :test do
    gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end

group :production do
  gem 'pg'
end
